command /copyBlockCoords:
	trigger:
		if executor is not a op:
			send "&cYou dont have permission to use this command!" to executor
			stop
		set {_targetBlock} to (executor's targeted block)
		if {_targetBlock} is not set:
			send "&cTarget block not found!" to executor
			stop
		set {_coordsRaw} to "%{_targetBlock}'s x coords%, %({_targetBlock}'s y coords + 1)%, %{_targetBlock}'s z coords%"
		send "<suggest command:%{_coordsRaw}%>&e%{_targetBlock}%&f: &e%{_coordsRaw}% &7(Click to Copy)<reset>" to executor

command /testGun [<player>] [<text>]:
	trigger:
		if executor is not console:
			if executor is not a op:
				send "&cYou dont have permission to use this command!" to executor
				stop
		set {_lore} to (arg 2)
		replace all "&" with "§" in {_lore}
		set slot 0 of arg 1's inventory to (iron hoe named "&aTEST GUN" with lore {_lore})